<h2>XML dict</h2>

<!-- Short description -->
<p>A list of MWEs in a reference gold standard.</p>


<h3>Characteristics</h3>

<p>See the generic <a href="PHITE.php?sitesig=MWE&page=MWE_060_File_types">XML description</a>.</p>



<h3>Details</h3>

[[Incomplete]]



<h3>Example</h3>

<p>You can have a look at a sample <a
href="http://sourceforge.net/p/mwetoolkit/code/HEAD/tree/test/filetype-samples/dict.xml">dict</a>
file.</p>

<hr/>

