<h2>XML patterns</h2>

<!-- Short description -->
<p>A list of regex-style patterns represented in XML.</p>


<h3>Characteristics</h3>

<p>See the generic <a href="PHITE.php?sitesig=MWE&page=MWE_060_File_types">XML description</a>.</p>



<h3>Details</h3>

<p>See <a href="PHITE.php?sitesig=MWE&page=MWE_030_Defining_Patterns">Defining Patterns</a>.</p>



<h3>Example</h3>

<p>You can have a look at a sample <a
href="http://sourceforge.net/p/mwetoolkit/code/HEAD/tree/test/filetype-samples/patterns.xml">patterns</a>
file.</p>

<hr/>

