<h2>ARFF file type</h2>

<!-- Short description -->
<p>
The "ARFF" file type is used by the WEKA Machine Learning toolkit to represent
a dataset.
</p>



<h3>Characteristics</h3>

<table border="1">
<tr><td><strong>String name<sup><a href="#fn1" id="ref1">1</a></sup></strong></td><td>"ARFF"</td></tr>
<tr><td><strong>Categories</strong></td><td>"candidates" (output only)</td></tr>
<tr><td><strong>Encoding</strong></td><td>Text file, UTF-8</td></tr>
<tr><td><strong>Source</strong></td><td>Standard of <a href="http://weka.wikispaces.com/ARFF">WEKA Toolkit</a></td></tr>
<tr><td><strong>Automatic detection</strong></td><td>No (it's output only)</td></tr>
</table>



<h3>Details</h3>

<p>You can read the <a href="http://weka.wikispaces.com/ARFF+%28stable+version%29">official ARFF definition</a>.</p>




<h3>Code comments</h3>

<p>As defined by WEKA, code comments are created by prefixing a line with the special character "%".</p>




<h3>Example</h3>

<p>You can have a look at a sample <a
href="http://sourceforge.net/p/mwetoolkit/code/HEAD/tree/test/filetype-samples/output-only/candidates.arff">candidates</a>
file.</p>

<hr/>



<sup id="fn1">1. Case-sensitive string to be used with script options such as <tt>--to</tt>.<a href="#ref1" title="Jump back to footnote 1 in the text.">↩</a></sup>
