
<h2>Contact</h2>

<p>A question? A bug? A suggestion? Please don't hesitate to send us an email:</p>

<p>Our username is <tt>mwetoolkit</tt> and the email provider is <strong>Gmail</strong>, can you guess our email address? ;-)</p>

<p>You can also subscribe to the <a href="https://groups.google.com/d/forum/mwetoolkit" target="_blank">public mailing list</a>.</p>

<hr/>

<h3>The Toolkit Developers</h3>

<p>The <tt>mwetoolkit</tt> is/was developed and maintained by:</p>

<ul>
<li><a href="http://www.inf.ufrgs.br/~ceramisch">Carlos Ramisch</a></li>
<li>Silvio Ricardo Cordeiro</li>
<li><a href="http://inf.ufrgs.br/~vbuaraujo/index.en.html">Vitor de Araujo</a></li>
<li>Sandra Castellanos</li>
<li>Maite Dupont</li>
</ul>

<p>Occasional contributors:</p>

<ul>
<li><a href="http://www.veneraarnaoudova.ca/">Venera Arnaoudova</a></li>
</ul>
