<h3>The Toolkit Developers</h3>

<p>The <tt>mwetoolkit</tt> is/was developed and maintained by:</p>

<ul>
<li><a href="http://www.inf.ufrgs.br/~ceramisch">Carlos Ramisch</a></li>
<li><a href="http://inf.ufrgs.br/~vbuaraujo/index.en.html">Vitor de Araujo</a></li>
<li>Sandra Castellanos</li>
<li>Maite Dupont</li>
<li>Silvio Ricardo Cordeiro</li>
</ul>

<p>Occasional contributors:</p>

<ul>
<li><a href="http://www.veneraarnaoudova.ca/">Venera Arnaoudova</a></li>
</ul>
