<h2>HTML file type</h2>

<!-- Short description -->
<p>
The "HTML" file type represents a (possibly annotated) corpus
in a way that can be more easily visualized by humans.
</p>



<h3>Characteristics</h3>

<table border="1">
<tr><td><strong>String name<sup><a href="#fn1" id="ref1">1</a></sup></strong></td><td>"HTML"</td></tr>
<tr><td><strong>Categories</strong></td><td>"corpus" (output only)</td></tr>
<tr><td><strong>Encoding</strong></td><td>Text file, UTF-8, HTML</td></tr>
<tr><td><strong>Source</strong></td><td>&mdash;</td></tr>
<tr><td><strong>Automatic detection</strong></td><td>No (it's output only)</td></tr>
</table>




<h3>Example</h3>

<p>You can have a look at a sample MWE-annotated <a
href="TED-English-sample.html">corpus</a>
file.</p>

<hr/>



<sup id="fn1">1. Case-sensitive string to be used with script options such as <tt>--to</tt>.<a href="#ref1" title="Jump back to footnote 1 in the text.">↩</a></sup>
